"""Cambios 

Revision ID: 2b2ca3893cf7
Revises: 
Create Date: 2022-05-05 00:57:36.125167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b2ca3893cf7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('trabajo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Personas')
    # ### end Alembic commands ###
